language: R
sudo: false
cache: packages
r:
  - release
  - devel

r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
