rm(list=ls())
options(shiny.trace=FALSE)
library(shiny)
library(stringr)
library(dplyr)
library(purrr)
library(tidyr)
library(qdap)
source("helper_functions.R")
safe_slashes                <- dplyr::failwith(NULL, half_slashes, F)
safe_highlight_test_str     <- dplyr::failwith(NULL, highlight_test_str, F)
safe_html_format_match_list <- dplyr::failwith(NULL, html_format_match_list, F)
safe_get_match_list         <- dplyr::failwith(NULL, get_match_list, F)

highlight_color_pallete <- "Set3"