rm(list=ls())
options(shiny.trace=FALSE)
library(shiny)
library(stringr)
library(dplyr)
library(qdap)
library(htmltools)
library(shinyBS)
source("helper_functions.R")
source("regexplainer.R")
safe_slashes                <- purrr::possibly(half_slashes, otherwise = NULL, quiet=FALSE)
safe_highlight_test_str     <- purrr::possibly(highlight_test_str, otherwise = NULL, quiet=FALSE)
safe_html_format_match_list <- purrr::possibly(html_format_match_list, otherwise = NULL, quiet=FALSE)
safe_get_match_list         <- purrr::possibly(get_match_list, otherwise = NULL, quiet=FALSE)

highlight_color_pallete <- "Set3"